### ISSUE TITLE
Add Self Injection

### ISSUE THREAD

**Issue by Simon-Davies** [icyguider/Nimcrypt2#8]
It would be worth adding self injection as an option. This is what S3cur3Th1sSh1t has in Nim Packer v1.2

**Comment by icyguider** [comment]
I might consider it at a later point, but for now you could always export your payload in the exe format and use the pe option if you want don't want it to run in a remote process. 

Also, I'm not necessarily trying to copy ShitSecure's packer feature for feature, as I still want there to be a good incentive for people to support him through Patreon as I think he deserves it. This tool wouldn't exist without his publicly available work, so I intend on always keeping it a bit behind his packer feature wise out of respect for him. I hope you understand :)

**Comment by Simon-Davies** [comment]
I pat to support him on Patreon as I agree with you :)
